# Generated by Django 6.0.3 on 2026-03-27 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producto",
            options={"ordering": ["nombre"], "verbose_name_plural": "Productos"},
        ),
        migrations.AddField(
            model_name="producto",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(blank=True),
        ),
    ]
