# Generated by Django 6.0.3 on 2026-04-08 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_movimientostock"),
        ("tiendas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="tienda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tiendas.tienda",
            ),
        ),
    ]
