# Generated by Django 6.0.3 on 2026-03-27 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="role",
            old_name="users",
            new_name="usuarios",
        ),
    ]
