# Generated by Django 6.0.3 on 2026-04-08 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiendas", "0001_initial"),
        ("users", "0002_rename_users_role_usuarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tienda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tiendas.tienda",
            ),
        ),
    ]
