# Generated by Django 6.0.3 on 2026-03-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="notas",
            field=models.TextField(blank=True, null=True),
        ),
    ]
