# Generated by Django 6.0.3 on 2026-03-31 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0002_venta_notas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorteCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_apertura", models.DateTimeField(auto_now_add=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "fondo_inicial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_efectivo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_tarjeta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_transferencia",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_ventas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("num_ventas", models.IntegerField(default=0)),
                (
                    "conteo_efectivo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "conteo_tarjeta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "conteo_transferencia",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "diferencia_efectivo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "diferencia_tarjeta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "diferencia_transferencia",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("abierto", "Abierto"), ("cerrado", "Cerrado")],
                        default="abierto",
                        max_length=10,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Corte de caja",
                "verbose_name_plural": "Cortes de caja",
                "ordering": ["-fecha_apertura"],
            },
        ),
    ]
