# Generated by Django 6.0.3 on 2026-04-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0003_cortecaja"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="total_devuelto",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
