# Generated by Django 6.0.3 on 2026-04-09 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiendas", "0001_initial"),
        ("ventas", "0004_venta_total_devuelto"),
    ]

    operations = [
        migrations.AddField(
            model_name="cortecaja",
            name="tienda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tiendas.tienda",
            ),
        ),
        migrations.AddField(
            model_name="devolucion",
            name="tienda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tiendas.tienda",
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="tienda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tiendas.tienda",
            ),
        ),
    ]
