# Generated by Django 6.0.3 on 2026-04-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0005_cortecaja_tienda_devolucion_tienda_venta_tienda"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="folio",
            field=models.IntegerField(default=0),
        ),
    ]
