# Generated by Django 6.0.3 on 2026-04-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tiendas", "0002_tienda_direccion_tienda_email_tienda_logo_and_more"),
        ("ventas", "0006_venta_folio"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="venta",
            unique_together={("tienda", "folio")},
        ),
    ]
