# Generated by Django 6.0.3 on 2026-04-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiendas", "0002_tienda_direccion_tienda_email_tienda_logo_and_more"),
        ("ventas", "0007_alter_venta_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="cortecaja",
            name="folio",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="cortecaja",
            unique_together={("tienda", "folio")},
        ),
    ]
