# Generated by Django 6.0.3 on 2026-04-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas", "0008_cortecaja_folio_alter_cortecaja_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cortecaja",
            name="folio",
            field=models.IntegerField(default=0),
        ),
    ]
