# Generated by Django 6.0.3 on 2026-04-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiendas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tienda",
            name="direccion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tienda",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="tienda",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
        migrations.AddField(
            model_name="tienda",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
