# Generated by Django 6.0.3 on 2026-04-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tiendas", "0002_tienda_direccion_tienda_email_tienda_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tienda",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="LOGOS_POS/"),
        ),
    ]
